user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

# Menambahkan daemon off agar Nginx berjalan di latar depan
daemon off;

events {
    worker_connections 1024;  # Meningkatkan batas koneksi untuk mengakomodasi lebih banyak koneksi simultan
    multi_accept on;
}

http {
    ##
    # Basic Settings
    ##
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;  # Mengurangi latensi untuk koneksi yang lebih cepat
    types_hash_max_size 2048;
    server_tokens off;
    client_body_temp_path /tmp;
    client_max_body_size 1000M;

    limit_req_zone $binary_remote_addr zone=dka:10m rate=10r/s;

    # Ukuran buffer untuk body dari client (misal: POST besar, form login token, dll)
    client_body_buffer_size 128k;
    # Ukuran buffer untuk HTTP header client (misal: banyak cookie, token, header custom)
    client_header_buffer_size 16k;
    # Buffer besar untuk menangani header panjang (seperti cookie/token/URL panjang)
    large_client_header_buffers 8 64k;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ##
    # SSL Settings
    ##
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;  # Menyertakan semua protokol SSL yang diperlukan
    ssl_prefer_server_ciphers on;

    ##
    # Logging Settings
    ##
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    ##
    # Gzip Settings
    ##
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;  # Tingkat kompresi yang seimbang
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    ##
    # Virtual Host Configs
    ##
    include /etc/nginx/conf.d/*.conf;
}
